labels:
  - name: bug
    color: 'd73a4a'
    description: Something isn't working
  - name: enhancement
    color: 'a2eeef'
    description: New feature or request
  - name: content
    color: 'cfd3d7'
    description: Content updates
  - name: infra
    color: '7057ff'
    description: Infrastructure tasks
